export const urlApi = {
  login: '/auth/signin',
  changePassWord: '/auth/users/changePassWord',
  department: '/departments',
  rank: '/ranks',
  personnel: '/personnels',
  timeSheet: '/timeSheets',
  bonus: '/bonus',
  personnelBonus: '/personnelBonus',
  allowance: '/allowances',
  fine: '/fines',
  personnelFine: '/personnelFines',
  personnelAllowance: '/personnelAllowances',
  summaryOfWorkingDays: '/timeSheets/summaryOfWorkingDays',
  user: '/auth/users',
  summaryOfSalary: '/timeSheets/summaryOfSalary',
}
