export const urlApi = {
  login: '/auth/signin',
  getProfile: '/auth/profile',
  changePassWord: '/user/changePassWord',
  department: '/departments',
  rank: '/ranks',
  personnel: '/personnels',
  timeSheet: '/timeSheets',
  bonus: '/bonus',
  personnelBonus: '/personnelBonus',
  allowance: '/allowances',
  fine: '/fines',
  personnelAllowance: '/personnelAllowances',
  summaryOfWorkingDays: '/timeSheets/summaryOfWorkingDays',
}
